apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-chaos-monkey
  name: k8s-chaos-monkey
spec:
  containers:
  - image: djkormo/chaos-monkey
    name: k8s-chaos-monkey
    env:
      - name: NAMESPACE
        value: "default"
      - name: DELAY
        value: "10"
      - name: EXLUDEDAPPS
        value: "k8s-chaos-monkey"
    resources:
      limits:
        cpu: "0.1"
        memory: "50Mi"
      requests:
        cpu: "0.1"
        memory: "50Mi"
    imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always

